name: Foxess V2 Scraper
version: 1.0.7
slug: foxess_v2_scraper
description: Browser-based scraper for Foxess V2 solar data
url: https://github.com/toolsinabox/foxess-v2-addon
arch:
  - aarch64
  - amd64
  - armv7
init: false
options:
  username: ""
  password: ""
  port: 8099
schema:
  username: str
  password: password
  port: port
ports:
  8099/tcp: 8099
ports_description:
  8099/tcp: Web API for scraper
build_from:
  aarch64: "ghcr.io/home-assistant/aarch64-base:latest"
  amd64: "ghcr.io/home-assistant/amd64-base:latest"
  armv7: "ghcr.io/home-assistant/armv7-base:latest"

